# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=200)),
                ('marks_scored', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ResumeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(verbose_name='DOB')),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField()),
                ('company_name', models.CharField(max_length=200)),
                ('role_in_company', models.CharField(max_length=2000)),
                ('leaving_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('rel_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.ResumeUser')),
            ],
        ),
        migrations.AddField(
            model_name='educationinformation',
            name='rel_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.ResumeUser'),
        ),
    ]
